package de.htw_berlin.movation.persistence.model;

import android.support.annotation.NonNull;

import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.misc.BaseDaoEnabled;

import java.util.Date;

public class Assignment extends BaseDaoEnabled {

    public enum Status{
        STARTED,
        COMPLETED,
        FAILED
    }

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int id;

    @NonNull
    @DatabaseField(foreign = true)
    public Goal goal;

    @DatabaseField(foreign = true)
    public User user;

    @DatabaseField(dataType = DataType.ENUM_INTEGER)
    public Status status;
    
    @DatabaseField
    public Date time;

    @SuppressWarnings("unused")
    public Assignment() {
    }

}