package de.htw_berlin.movation.persistence.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.misc.BaseDaoEnabled;

public class Goal extends BaseDaoEnabled {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int id;

    @DatabaseField
    public String description;

    @DatabaseField
    public String requirements;

    @DatabaseField(foreign = true)
    public GoalCategory category;

    @SuppressWarnings("unused")
    public Goal() {
    }

}