package de.htw_berlin.movation.persistence.model;

import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.misc.BaseDaoEnabled;

public class Movatar extends BaseDaoEnabled {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int id;

    @DatabaseField(dataType = DataType.ENUM_INTEGER)
    public Constants.SkinColor skinColor;

    @DatabaseField(dataType = DataType.ENUM_INTEGER)
    public Constants.Fitness fitness;

    @DatabaseField(dataType = DataType.ENUM_INTEGER)
    public Constants.Sex sex;

    @DatabaseField(dataType = DataType.ENUM_INTEGER)
    public Constants.Haircut haircut;

    @DatabaseField(dataType = DataType.ENUM_INTEGER)
    public Constants.Face face;

    @DatabaseField(foreign = true)
    public MovatarClothes clothing1;

    @DatabaseField(foreign = true)
    public MovatarClothes clothing2;

    @DatabaseField(foreign = true)
    public MovatarClothes clothing3;

    @DatabaseField(foreign = true)
    public User user;




    @SuppressWarnings("unused")
    public Movatar() {
    }
}