package de.htw_berlin.movation.persistence.model;

import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.misc.BaseDaoEnabled;

import java.io.File;
import java.sql.SQLException;

public class MovatarClothes extends BaseDaoEnabled {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int id;

    @DatabaseField(dataType = DataType.ENUM_INTEGER)
    public Constants.Fitness fitness;

    @DatabaseField(dataType = DataType.ENUM_INTEGER)
    public Constants.Sex sex;

    @DatabaseField
    public String type;

    @DatabaseField
    public String name;

    @DatabaseField
    public long price;

    @DatabaseField
    public String imageFilePath;

    @SuppressWarnings("unused")
    public MovatarClothes() {
    }

    @Override
    public int delete() throws SQLException {
        new File(imageFilePath).delete();
        return super.delete();
    }
}