package de.htw_berlin.movation.persistence.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.misc.BaseDaoEnabled;

public class Mrg_User_MovatarClothes extends BaseDaoEnabled {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int id;

    @DatabaseField(foreign = true)
    public User user;

    @DatabaseField(foreign = true)
    public MovatarClothes movatarClothes;

    @SuppressWarnings("unused")
    public Mrg_User_MovatarClothes() {
    }

}