package de.htw_berlin.movation.persistence.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.misc.BaseDaoEnabled;

import java.util.Collection;

public class User extends BaseDaoEnabled {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int id;

    @DatabaseField(index = true)
    public String mailAddress;

    @DatabaseField
    public String firstName;

    @DatabaseField
    public String lastName;

    @DatabaseField
    public String password;

    @DatabaseField
    /**
     * unused
     */
    public long credits;

    @ForeignCollectionField
    Collection<Discount> discounts;

    @ForeignCollectionField
    Collection<Assignment> assignments;

    @SuppressWarnings("unused")
    public User() {
    }

}