package de.htw_berlin.movation.persistence;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.misc.BaseDaoEnabled;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class User extends BaseDaoEnabled {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int id;

    @DatabaseField(index = true)
    public String mailAddress;

    @DatabaseField
    public String firstName;

    @DatabaseField
    public String lastName;

    @SuppressWarnings("unused")
    public User() {
    }

}